version: '3.9'

services:
  budgetmenotweb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=BudgetMeNotDb;Username=postgres;Password=DummyPassword
    volumes:
      - dataprotection-keys:/app/keys
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: BudgetMeNotDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DummyPassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  dataprotection-keys:
  postgres-data:
