version: '3.9'

services:
  budgetmenotweb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=BudgetMeNotDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    volumes:
      - dataprotection-keys:/app/keys
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
volumes:
  dataprotection-keys: